### ISSUE TITLE
KarpusStrongPoly 1.0.1 crashes Rack 1.0b4 on MAcOS X when adding

### ISSUE THREAD

**Issue by fractalgee** [baconpaul/BaconPlugs#30] opened 2019-06-18 07:39 UTC
The KarplusStronPoly Module crashes Rack 1.0b4 on MAcOS X 10.11.6 when it's being added.

Here is the backtrace of the crashing thread:

```
Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

VM Regions Near 0:
--> 
    __TEXT                 000000010d756000-000000010dbdd000 [ 4636K] r-x/rwx SM=COW  /Applications/Rack.app/Contents/MacOS/Rack

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   plugin.dylib                  	0x000000010f3fa441 KarplusStrongPoly::KarplusStrongPoly() + 1809
1   plugin.dylib                  	0x000000010f3f9c72 rack::plugin::Model* rack::createModel<KarplusStrongPoly, KarplusStrongPolyWidget>(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)::TModel::createModuleWidget() + 34
2   com.vcvrack.rack              	0x000000010d800b78 rack::app::chooseModel(rack::plugin::Model*) + 24
3   com.vcvrack.rack              	0x000000010d800608 rack::app::ModelBox::onButton(rack::event::Button const&) + 56
4   com.vcvrack.rack              	0x000000010d7d9938 rack::widget::Widget::onButton(rack::event::Button const&) + 200
5   com.vcvrack.rack              	0x000000010d7d9938 rack::widget::Widget::onButton(rack::event::Button const&) + 200
6   com.vcvrack.rack              	0x000000010d7d9938 rack::widget::Widget::onButton(rack::event::Button const&) + 200
7   com.vcvrack.rack              	0x000000010d81d228 rack::ui::ScrollWidget::onButton(rack::event::Button const&) + 200
8   com.vcvrack.rack              	0x000000010d7da5a8 rack::widget::OpaqueWidget::onButton(rack::event::Button const&) + 200
9   com.vcvrack.rack              	0x000000010d7da5a8 rack::widget::OpaqueWidget::onButton(rack::event::Button const&) + 200
10  com.vcvrack.rack              	0x000000010d7ff452 rack::app::BrowserOverlay::onButton(rack::event::Button const&) + 18
11  com.vcvrack.rack              	0x000000010d7da5a8 rack::widget::OpaqueWidget::onButton(rack::event::Button const&) + 200
12  com.vcvrack.rack              	0x000000010d7baf59 rack::event::State::handleButton(rack::math::Vec, int, int, int) + 73
13  com.apple.AppKit              	0x00007fff8a4973c9 -[NSWindow _handleMouseDownEvent:isDelayedEvent:] + 6322
14  com.apple.AppKit              	0x00007fff8a4983ad -[NSWindow _reallySendEvent:isDelayedEvent:] + 212
15  com.apple.AppKit              	0x00007fff89ed7539 -[NSWindow sendEvent:] + 517
16  com.apple.AppKit              	0x00007fff89e57a38 -[NSApplication sendEvent:] + 2540
17  com.vcvrack.rack              	0x000000010d831d47 _glfwPlatformPollEvents + 119
18  com.vcvrack.rack              	0x000000010d7d4e1a rack::Window::run() + 138
19  com.vcvrack.rack              	0x000000010d7c0884 main + 1076
20  com.vcvrack.rack              	0x000000010d758034 start + 52
```

**Comment by baconpaul** [comment] 2019-06-18 12:40
I'm sorry you experienced this crash and appreciate the clear report.

With the current source build of Rack v1 on macOS with the release_v1.0.1 bacon music source, though I can't reproduce it. 

But when I download the latest binary rack build (dev.b4bd09a - is that what you mean by beta 4?) and grab the plugin from the plugin manager I do indeed get a crash. And when I run the latest Rack against the same staged binary, I also get a crash.

So somehow the build from the plugin manager is different than the build form my source. I will have to go ask @cschol about this.

**Comment by baconpaul** [comment] 2019-06-18 12:43
Oh no need to ask @cshol. I see the bug. I am amazed it didn't crash for me. Thank you. I"ll try and get a fix together.

**Comment by fractalgee** [comment] 2019-06-18 12:58
yes, that is the build, the one currently posted at VCVRack.com/Rack.html

and no worries, these things happen, it';s all still dev anyhow and I am
happy to file whatever I encounter so it can be fixed prior to 1.0 release.

**Comment by baconpaul** [comment] 2019-06-18 13:08
Thanks! And yeah please keep em coming. Good bug reports make good software!

I have pushed a fix and did updated builds (I also made it so master always updates my builds). Can you grab the latest mac zip from here:

https://github.com/baconpaul/BaconPlugs/releases

and confirm it also works for you? If so I will update the version and community library.

Appreciated

**Comment by fractalgee** [comment] 2019-06-18 13:10
Been dealing with software for more than 30 years and have filed thousands
of issues in that time so all good. I like to have things break and hope I
can give enough info for the dev to fix whatever caused it unless I already
know....  So all good, I have been a beta tester for about as long as well
so I am used to moving targets

**Comment by baconpaul** [comment] 2019-06-18 13:14
Cool. Well I just tried the new zip in the released version and it didn't crash for me; if it doesn't crash for you I can get it as 1.0.2 in community.

 (I am presuming you know how to test a downloaded rack plugin set; but in the event you don't, download that zip file and it will unzip to a file called "BaconMusic". Go to ~/Documents/Rack/plugins-v1 and delete the BaconMusic folder there, and replace it with the one you just downloaded. Then run Rack normally. If KSPoly doesn't crash and shows version 1.0.6dc... we are golden. If it does crash grab another BaconMusic module and make sure that the version slows 1.0.6dcwhatever. And to see the version right mouse on any plugin and choose plugin/version).

**Comment by fractalgee** [comment] 2019-06-18 13:19
@baconpaul: I just tried the last build you posted here and that works despite one little issue:

![KarPlusPoly_KnobMissing](https://user-images.githubusercontent.com/12473856/59685346-418b6d80-91dc-11e9-8fc9-706c8731daca.png)

There is a knob missing in the Filter section.

So no more crash but not quite fully functional. Works in all other ways though....

**Comment by baconpaul** [comment] 2019-06-18 13:19
Oh great. Yeah that knob is missing on purpose; I only have one filter type coded right now so there's nothing to choose. When a snap knob only has one value it grays out. 

Thank you very much for the confirmation. Very much appreciated!

**Closed as completed** 2019-06-18 13:21 UTC
